### ISSUE TITLE
Travis does not seem to be enabled on the repo

### ISSUE THREAD

**Issue by stof** [platformsh/console-form#2]
There is a Travis config file, and the readme tries to display the Travis badge, but clicking on the link says that the repo cannot be found on Travis.

**Comment by pjcdawkins** [comment]
Right, although I was allowed to create the repo, I'm just waiting for an organizational admin @platformsh to enable Travis

**Comment by pjcdawkins** [comment]
While I wait... I'm running tests on my fork. I've updated the badge/link URL.
