### ISSUE TITLE
Your package is missing the LICENSE file

### ISSUE THREAD

**Issue by stof** [platformsh/console-form#3]
There is no license in this package (and no license info in the composer.json either).

This effectively means that your project is proprietary, even if the source code is public

**Comment by stof** [comment]
you should also add the LICENSE file at the root IMO (btw, this will allow the license to be detected by the new github license API)

**Comment by pjcdawkins** [comment]
Fair enough. Thanks for the PR / issues!

Note that (as the version number [indicates](http://semver.org/)) this project is new and not stable - not that I intend to change much.

**Comment by stof** [comment]
@pjcdawkins this is not a reason to omit the license though (it would be a pain if people actually start contributing and then you change the license to an open-source one, as you would have to ask them all to agree about the change)

**Comment by stof** [comment]
btw, to avoid any issue by a picky legal guy, I'm fine with the MIT license (I'm the only contributor except you in the history)
